### ISSUE TITLE
Numbered lists are not contiguous 

### ISSUE THREAD

**Issue by philsturgeon** [bump-sh/docs#159]
The Huma guide has some rendering issues with number lists resetting to 1 after a code block. it should continue with the number provided.

<img width="533" alt="Screenshot 2023-12-18 at 1 54 43 PM" src="https://github.com/bump-sh/docs/assets/67381/26d63657-9184-49f3-a9c8-024db70a669b">

The Fast API guide has the same issue.

<img width="419" alt="Screenshot 2023-12-18 at 1 56 03 PM" src="https://github.com/bump-sh/docs/assets/67381/7ab625b6-ca61-4d2b-9dc0-bb4f29736dd0">

**Comment by thimy** [comment]
Hey Phil, thanks for reporting this!

I just opened a PR fixing the issue, which is more about how to handle kramdown, the markdown parser, than a bugfix.

The key to make it work is to not leave any empty line after the ordered list item and line-up the block to the start of the item paragraph so the parser gets that the following block is part of it.

Let me know if I can help you any further 💁‍♀️

**Comment by philsturgeon** [comment]
Thanks for fixing it. 

Another option to consider would be ditching the fairly useless kramdown for something CommonMark based. Bridgetown supports customer parsers and there's plenty of Gems.

https://www.bridgetownrb.com/docs/configuration/markdown

For more on why you might want to do that, I wrote about how subtle differences in markdown can cause hell for teams using a lot of markdown: https://philsturgeon.com/state-of-markdown/
