### ISSUE TITLE
Add top nav links

### ISSUE THREAD

**Issue by ChristopheDujarric** [bump-sh/docs#36]
We want to give a quick access for our content hub visitors to the following resources, via the top nav bar.
* Go to Bump.sh (as a visitor)/go to the user dashboard (as a user)
* Sign-in/sign-up (can we know if the user is signed in?)
* Go to the Bump.sh API reference doc.

This also requires some design, to avoid rendering as below:
<img width="405" alt="Capture d’écran 2023-02-06 à 14 43 49" src="https://user-images.githubusercontent.com/30788/216987019-d08089ee-3ab7-4478-ba10-28ec4cbbaacf.png">

**Comment by paulRbr** [comment]
fixed by #56 ?

**Comment by ChristopheDujarric** [comment]
Absolutely!
