### ISSUE TITLE
Migrate from GitHub hosting to Netlify

### ISSUE THREAD

**Issue by scharrier** [bump-sh/docs#7]
Here are the required feature for hosting the content hub:
* custom domain support
* https support
* URL rewriting server side (from config)

Here are nice-to-have ones:
* Preview on PRs (= 1 URL per PR on which we can preview the future rendering. Note that it shouldn't be indexed by SEs)

**Comment by paulRbr** [comment]
:white_check_mark: For now it's deployed on a `Bump` team with a free plan with my account (linked to my GH account).

Adding extra members costs 15 $/month per member.
