### ISSUE TITLE
Global design

### ISSUE THREAD

**Issue by ChristopheDujarric** [bump-sh/docs#8]
Inspiration sources:
https://segment.com/docs/ (thank you @scharrier ❤️)
https://rapidapi.com/learn
https://docusaurus.io/showcase
* https://docs.dyte.io/
* https://developer.redis.com/
* https://refine.dev/ (menus)
* https://hub.qovery.com/

**Comment by scharrier** [comment]
@antlio can we start working on this one soon? Maybe we should organise some kind of kick-off?
